# Players to evaluate
hitters = {
    "Aaron Judge": "j/judgeaa01.shtml",
    "Adley Rutschmann": "r/rutscad01.shtml",
    "Alec Bohm": "b/bohmal01.shtml",
    "Alec Burleson": "b/burleal01.shtml",
    "Alex Bregman": "b/bregmal01.shtml",
    "Anthony Santander": "s/santaan02.shtml",
    "Austin Riley": "r/rileyau01.shtml",
    "Bobby Witt Jr": "w/wittbo02.shtml",
    "Brandon Lowe": "l/lowebr01.shtml",
    "Brandon Marsh": "m/marshbr02.shtml",
    "Brandon Nimmo": "n/nimmobr01.shtml",
    "Brent Rooker": "r/rookebr01.shtml",
    "Brenton Doyle": "d/doylebr02.shtml",
    "Bryan De La Cruz": "d/delacbr01.shtml",
    "Bryan Reynolds": "r/reynobr01.shtml",
    "Bryce Harper": "h/harpebr03.shtml",
    "Byron Buxton": "b/buxtoby01.shtml",
    "Cal Raleigh": "r/raleica01.shtml",
    "Cedric Mullins": "m/mullice01.shtml",
    "Charlie Blackmon": "b/blackch02.shtml",
    "Christopher Morel": "m/morelch01.shtml",
    "CJ Abrams": "a/abramcj01.shtml",
    "Colt Keith": "k/keithco01.shtml",
    "Colton Cowser": "c/cowseco01.shtml",
    "Corbin Carroll": "c/carroco01.shtml",
    "Corey Seager": "s/seageco01.shtml",
    "Dansby Swanson": "s/swansda01.shtml",
    "Dylan Carlson": "c/carlsdy01.shtml",
    "Elly De La Cruz": "d/delacel01.shtml",
    "Enrique Hernandez": "h/hernaen02.shtml",
    "Ezequiel Tovar": "t/tovarez01.shtml",
    "Francisco Lindor": "l/lindofr01.shtml",
    "Gary Sanchez": "s/sanchga02.shtml",
    "Gavin Lux": "l/luxga01.shtml",
    "George Springer": "s/springe01.shtml",
    "Gleyber Torres": "t/torregl01.shtml",
    "Gunnar Henderson": "h/hendegu01.shtml",
    "Heliot Ramos": "r/ramoshe02.shtml",
    "Hunter Renfroe": "r/renfrhu01.shtml",
    "Ian Happ": "h/happia01.shtml",
    "Isiah Kiner-Falefa": "k/kineris01.shtml",
    "J.D. Martinez": "m/martijd02.shtml",
    "J.T Realmuto": "r/realmjt01.shtml",
    "Jackson Chourio": "c/chourja01.shtml",
    "Jake Burger": "b/burgeja01.shtml",
    "Jake Cave": "c/caveja01.shtml",
    "Jake Cronenworth": "c/croneja01.shtml",
    "Jake McCarthy": "m/mccarja02.shtml",
    "Jarren Duran": "d/duranja01.shtml",
    "Jason Heyward": "h/heywaja01.shtml",
    "Jazz Chisholm Jr": "c/chishja01.shtml",
    "Jeimer Candelario": "c/candeje01.shtml",
    "Jeremy Pena": "p/penaje02.shtml",
    "Jesus Sanchez": "s/sanchje02.shtml",
    "Joc Pederson": "p/pederjo01.shtml",
    "Jonah Bride": "b/bridejo01.shtml",
    "Jonathan India": "i/indiajo01.shtml",
    "Jorge Polanco": "p/polanjo01.shtml",
    "Jorge Soler": "s/solerjo01.shtml",
    "Jose Altuve": "a/altuvjo01.shtml",
    "Jose Ramirez": "r/ramirjo01.shtml",
    "Josh Bell": "b/belljo02.shtml",
    "Josh Naylor": "n/naylojo01.shtml",
    "Josh Smith": "s/smithjo11.shtml",
    "Juan Soto": "s/sotoju01.shtml",
    "Juan Yepez": "y/yepezju01.shtml",
    "Julio Rodriguez": "r/rodriju01.shtml",
    "Jurickson Profar": "p/profaju01.shtml",
    "Justyn-Henry Malloy": "m/malloju02.shtml",
    "Ketel Marte": "m/marteke01.shtml",
    "Kyle Schwarber": "s/schwaky01.shtml",
    "LaMonte Wade Jr": "w/wadela01.shtml",
    "Lane Thomas": "t/thomala02.shtml",
    "Lawrence Butler": "b/butlela01.shtml",
    "Luis Arraez": "a/arraelu01.shtml",
    "Luis Rengifo": "r/rengilu01.shtml",
    "Luis Robert Jr": "r/roberlu01.shtml",
    "Luke Raley": "r/raleylu01.shtml",
    "Maikel Garcia": "g/garcima01.shtml",
    "Manny Machado": "m/machama01.shtml",
    "Marcell Ozuna": "o/ozunama01.shtml",
    "Marcus Semien": "s/semiema01.shtml",
    "Mark Canha": "c/canhama01.shtml",
    "Masataka Yoshida": "y/yoshima02.shtml",
    "Masyn Winn": "w/winnma01.shtml",
    "Matt Chapman": "c/chapmma01.shtml",
    "Matt Olson": "o/olsonma02.shtml",
    "Matt Vierling": "v/vierlma01.shtml",
    "Miguel Andujar": "a/andujmi01.shtml",
    "Mike Yastrzemski": "y/yastrmi01.shtml",
    "Nathaniel Lowe": "l/lowena01.shtml",
    "Nolan Arenado": "a/arenano01.shtml",
    "Oneil Cruz": "c/cruzon01.shtml",
    "Patrick Bailey": "b/bailepa01.shtml",
    "Paul Goldschmidt": "g/goldspa01.shtml",
    "Pete Alonso": "a/alonspe01.shtml",
    "Rafael Devers": "d/deverra01.shtml",
    "Randy Arozarena": "a/arozara01.shtml",
    "Rob Refsnyder": "r/refsnro01.shtml",
    "Rowdy Tellez": "t/tellero01.shtml",
    "Royce Lewis": "l/lewisro02.shtml",
    "Ryan McMahon": "m/mcmahry01.shtml",
    "Ryan Mountcastle": "m/mountry01.shtml",
    "Ryan O'Hearn": "o/ohearry01.shtml",
    "Salvador Perez": "p/perezsa02.shtml",
    "Sean Murphy": "m/murphse01.shtml",
    "Seiya Suzuki": "s/suzukse01.shtml",
    "Shohei Ohtani": "o/ohtansh01.shtml",
    "Spencer Steer": "s/steersp01.shtml",
    "Steven Kwan": "k/kwanst01.shtml",
    "Stuart Fairchild": "f/faircst01.shtml",
    "Teoscar Hernandez": "h/hernate01.shtml",
    "Trea Turner": "t/turnetr01.shtml",
    "Trevor Larnach": "l/larnatr01.shtml",
    "Ty France": "f/francty01.shtml",
    "Tyler Fitzgerald": "f/fitzgty01.shtml",
    "Victor Robles": "r/roblevi01.shtml",
    "Vinnie Pasquantino": "p/pasquvi01.shtml",
    "Vladimir Guerrero Jr": "g/guerrvl02.shtml",
    "Wenceel Perez": "p/perezwe01.shtml",
    "Will Smith": "s/smithwi05.shtml",
    "William Contretas": "c/contrwi02.shtml",
    "Willy Adames": "a/adamewi01.shtml",
    "Wyatt Langford": "l/langfwy01.shtml",
    "Xander Bogaerts": "b/bogaexa01.shtml",
    "Xavier Edwards": "e/edwarxa01.shtml",
    "Yandy Diaz": "d/diazya01.shtml",
    "Yordan Alvarez": "a/alvaryo01.shtml",
}


# myKeys = list(players.keys())
# myKeys.sort()
# sorted_dict = {i: players[i] for i in myKeys}

# print(sorted_dict)
